apiVersion: v1
kind: Secret
metadata:
  name: milvus-minio
  namespace: data-services
type: Opaque
stringData:
  host: minio.data-services.svc.cluster.local
  port: "9000"
  accesskey: minioadmin
  secretkey: minioadmin123
  bucket: milvus-bucket
