apiVersion: v1
kind: Service
metadata:
  name: kafka-java-producer-template
spec:
  type: ClusterIP
  selector:
    app: kafka-java-producer-template
  ports:
    - name: metrics
      port: 9302
      targetPort: metrics
