apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: av-technicals
  namespace: mlops
  labels:
    app.kubernetes.io/name: alphavantage-technicals
    data-provider: alphavantage
spec:
  serviceAccountName: argo-workflow
  entrypoint: run
  arguments:
    parameters:
      - name: symbols
        value: "IBM,AAPL"
      - name: indicator
        value: "SMA"
      - name: interval
        value: "daily"
      - name: time_period
        value: "20"
      - name: series_type
        value: "close"
      - name: target_bucket
        value: av-raw
  templates:
    - name: run
      inputs:
        parameters:
          - name: symbols
          - name: indicator
          - name: interval
          - name: time_period
          - name: series_type
          - name: target_bucket
      steps:
        - - name: load
            templateRef:
              name: av-bulk
              template: run
            arguments:
              parameters:
                - name: category
                  value: technicals
                - name: symbols
                  value: "{{inputs.parameters.symbols}}"
                - name: target_bucket
                  value: "{{inputs.parameters.target_bucket}}"
                - name: extra_params
                  value: |
                    {"indicator":"{{inputs.parameters.indicator}}","interval":"{{inputs.parameters.interval}}","time_period":{{inputs.parameters.time_period}},"series_type":"{{inputs.parameters.series_type}}"}
