apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: av-earnings
  namespace: mlops
  labels:
    app.kubernetes.io/name: alphavantage-earnings
    data-provider: alphavantage
spec:
  serviceAccountName: argo-workflow
  entrypoint: run
  arguments:
    parameters:
      - name: symbols
        value: "IBM,AAPL,MSFT"
      - name: target_bucket
        value: av-raw
  templates:
    - name: run
      inputs:
        parameters:
          - name: symbols
          - name: target_bucket
      steps:
        - - name: load
            templateRef:
              name: av-bulk
              template: run
            arguments:
              parameters:
                - name: category
                  value: earnings
                - name: symbols
                  value: "{{inputs.parameters.symbols}}"
                - name: target_bucket
                  value: "{{inputs.parameters.target_bucket}}"
