apiVersion: v1
kind: Secret
metadata:
  name: pipeline-source-credentials
  namespace: mlops
type: Opaque
stringData:
  PIPELINE_HTTP_AUTH_HEADER: ""
  PIPELINE_REST_API_TOKEN: ""
  PIPELINE_S3_ENDPOINT: minio.data-services.svc.cluster.local:9000
  PIPELINE_S3_ACCESS_KEY: minioadmin
  PIPELINE_S3_SECRET_KEY: minioadmin123
  PIPELINE_S3_REGION: us-east-1

