apiVersion: v1
kind: Secret
metadata:
  name: pipeline-sink-credentials
  namespace: mlops
type: Opaque
stringData:
  PIPELINE_MINIO_ENDPOINT: http://minio.data-services.svc.cluster.local:9000
  PIPELINE_MINIO_ACCESS_KEY: svc-pipelines
  PIPELINE_MINIO_SECRET_KEY: svc-pipelines-change-me
  PIPELINE_MINIO_REGION: us-east-1
  PIPELINE_MINIO_BUCKET_RAW: pipeline-raw
  PIPELINE_MINIO_BUCKET_PROCESSED: pipeline-processed
  PIPELINE_POSTGRES_DSN: postgresql://dagster:dagster123@postgresql.data-services.svc.cluster.local:5432/dagster
  PIPELINE_SOURCE_POSTGRES_DSN: postgresql://dagster:dagster123@postgresql.data-services.svc.cluster.local:5432/dagster
  PIPELINE_MILVUS_HOST: milvus.data-services
  PIPELINE_MILVUS_PORT: "19530"
  PIPELINE_CHROMA_HOST: chromadb.data-services
  PIPELINE_CHROMA_PORT: "8000"
  PIPELINE_DATAHUB_ENABLED: "true"
  PIPELINE_DATAHUB_GMS_URL: http://datahub-datahub-gms.data-services.svc.cluster.local:8080
  PIPELINE_DATAHUB_TOKEN: "__SET_DATAHUB_TOKEN__"
  PIPELINE_DATAHUB_ENV: PROD
  PIPELINE_ICEBERG_CATALOG_URI: http://datahub-datahub-gms.data-services.svc.cluster.local:8080/iceberg
  PIPELINE_ICEBERG_WAREHOUSE: s3://iceberg-warehouse/
  PIPELINE_MODEL_BUCKET: model-registry
  PIPELINE_AQP_API_URL: http://api.aqp.svc.cluster.local:8000
  PIPELINE_AQP_API_TOKEN: "__SET_AQP_API_TOKEN__"

