apiVersion: v1
kind: Secret
metadata:
  name: pipeline-sink-credentials
  namespace: mlops
type: Opaque
stringData:
  PIPELINE_MINIO_ENDPOINT: http://minio.data-services.svc.cluster.local:9000
  PIPELINE_MINIO_ACCESS_KEY: minioadmin
  PIPELINE_MINIO_SECRET_KEY: minioadmin123
  PIPELINE_MINIO_REGION: us-east-1
  PIPELINE_MINIO_BUCKET_RAW: dagster-artifacts
  PIPELINE_MINIO_BUCKET_PROCESSED: dagster-artifacts
  PIPELINE_POSTGRES_DSN: postgresql://dagster:dagster123@postgresql.data-services.svc.cluster.local:5432/dagster
  PIPELINE_SOURCE_POSTGRES_DSN: postgresql://dagster:dagster123@postgresql.data-services.svc.cluster.local:5432/dagster
  PIPELINE_MILVUS_HOST: milvus.data-services
  PIPELINE_MILVUS_PORT: "19530"
  PIPELINE_CHROMA_HOST: chromadb.data-services
  PIPELINE_CHROMA_PORT: "8000"

