apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: data-services

resources:
  - configmap.yaml
  - service.yaml
  - deployment.yaml

commonLabels:
  app.kubernetes.io/part-of: rpi-k8s-platform
  data-provider: alphavantage
