apiVersion: v1
kind: ServiceAccount
metadata:
  name: model-serving
  namespace: ml-platform
  annotations:
    serving.kserve.io/s3-endpoint: "minio.data-services.svc.cluster.local:9000"
    serving.kserve.io/s3-usehttps: "0"
    serving.kserve.io/s3-region: "us-east-1"
    serving.kserve.io/s3-useanoncredential: "false"
secrets:
  - name: model-storage-credentials
