apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: data-services

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: kafka-python-consumer-template
  app.kubernetes.io/part-of: rpi-k8s-platform
  app.kubernetes.io/component: consumer
