apiVersion: v1
kind: Service
metadata:
  name: kafka-python-consumer-template
  labels:
    app: kafka-python-consumer-template
spec:
  type: ClusterIP
  selector:
    app: kafka-python-consumer-template
  ports:
    - name: metrics
      port: 9301
      targetPort: metrics
      protocol: TCP
