plugins {
    id 'application'
    id 'com.gradleup.shadow' version '8.3.0'
    id 'java'
}

group = 'io.rpi.kafka.sample'
version = '0.1.0'

sourceCompatibility = JavaVersion.VERSION_17
targetCompatibility = JavaVersion.VERSION_17

repositories {
    mavenCentral()
}

dependencies {
    implementation "org.apache.kafka:kafka-clients:${kafkaVersion}"
    implementation "io.apicurio:apicurio-registry-serdes-avro-serde:${apicurioVersion}"
    implementation "org.apache.avro:avro:${avroVersion}"

    implementation "io.micrometer:micrometer-core:${micrometerVersion}"
    implementation "io.micrometer:micrometer-registry-prometheus:${micrometerVersion}"

    implementation "io.opentelemetry:opentelemetry-api:${otelVersion}"

    implementation "org.slf4j:slf4j-api:${slf4jVersion}"
    implementation "org.apache.logging.log4j:log4j-slf4j2-impl:${log4jVersion}"
    implementation "org.apache.logging.log4j:log4j-api:${log4jVersion}"
    implementation "org.apache.logging.log4j:log4j-core:${log4jVersion}"
}

application {
    mainClass = 'io.rpi.kafka.sample.consumer.ConsumerApp'
}

shadowJar {
    archiveClassifier.set('')
    mergeServiceFiles()
    manifest {
        attributes 'Main-Class': 'io.rpi.kafka.sample.consumer.ConsumerApp'
    }
}
