apiVersion: v1
kind: ConfigMap
metadata:
  name: polaris-config
  namespace: data-services
data:
  application.properties: |
    polaris.realm-context.realms=POLARIS
    polaris.features."SKIP_CREDENTIAL_SUBSCOPING_INDIRECTION"=true
    polaris.features."ALLOW_SETTING_S3_ENDPOINTS"=true
    quarkus.otel.sdk.disabled=true
