apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: data-services

resources:
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/name: polaris
      app.kubernetes.io/component: iceberg-catalog
      app.kubernetes.io/part-of: rpi-k8s-platform
