apiVersion: v1
kind: Service
metadata:
  name: kafka-python-producer-template
  labels:
    app: kafka-python-producer-template
spec:
  type: ClusterIP
  selector:
    app: kafka-python-producer-template
  ports:
    - name: metrics
      port: 9300
      targetPort: metrics
      protocol: TCP
