apiVersion: v1
kind: Service
metadata:
  name: kafka-java-consumer-template
spec:
  type: ClusterIP
  selector:
    app: kafka-java-consumer-template
  ports:
    - name: metrics
      port: 9303
      targetPort: metrics
