apiVersion: v1
kind: ConfigMap
metadata:
  name: datahub-ingestion-recipes
  namespace: data-services
  labels:
    app.kubernetes.io/name: datahub
    app.kubernetes.io/component: metadata-ingestion
data:
  recipe-postgres.yaml: |
    source:
      type: postgres
      config:
        host_port: ${INGEST_POSTGRES_HOST_PORT}
        database: ${INGEST_POSTGRES_DATABASE}
        username: ${INGEST_POSTGRES_USERNAME}
        password: ${INGEST_POSTGRES_PASSWORD}
        include_tables: true
        include_views: true
        stateful_ingestion:
          enabled: true
          remove_stale_metadata: true

    sink:
      type: datahub-rest
      config:
        server: ${DATAHUB_GMS_SERVER}
        token: ${DATAHUB_TOKEN}

  recipe-minio-s3.yaml: |
    source:
      type: s3
      config:
        path_specs:
          - include: "s3://argo-workflows/**"
          - include: "s3://dagster-artifacts/**"
          - include: "s3://mlflow-artifacts/**"
          - include: "s3://pipeline-raw/**"
          - include: "s3://pipeline-processed/**"
        aws_config:
          aws_access_key_id: ${INGEST_MINIO_ACCESS_KEY}
          aws_secret_access_key: ${INGEST_MINIO_SECRET_KEY}
          aws_endpoint_url: "http://${INGEST_MINIO_ENDPOINT}"
          aws_region: ${INGEST_MINIO_REGION}
        profiling:
          enabled: false
        stateful_ingestion:
          enabled: true
          remove_stale_metadata: true

    sink:
      type: datahub-rest
      config:
        server: ${DATAHUB_GMS_SERVER}
        token: ${DATAHUB_TOKEN}

  recipe-mlflow.yaml: |
    source:
      type: mlflow
      config:
        tracking_uri: ${INGEST_MLFLOW_TRACKING_URI}

    sink:
      type: datahub-rest
      config:
        server: ${DATAHUB_GMS_SERVER}
        token: ${DATAHUB_TOKEN}
