apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: datahub
  namespace: data-services
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
spec:
  ingressClassName: nginx
  rules:
    - host: datahub.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: datahub-datahub-frontend
                port:
                  number: 9002
