apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: data-services

resources:
  - secrets.yaml
  - secret-ingestion-secrets.yaml
  - ingress.yaml
  - configmap-ingestion-settings.yaml
  - configmap-ingestion-recipes.yaml
  - configmap-metadata-bridge.yaml
  - cronjob-ingest-postgres.yaml
  - cronjob-ingest-minio-s3.yaml
  - cronjob-ingest-mlflow.yaml
  - cronjob-metadata-bridge.yaml

commonLabels:
  app.kubernetes.io/name: datahub
  app.kubernetes.io/component: data-catalog
  app.kubernetes.io/part-of: rpi-k8s-platform
