apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: data-services

resources:
  - secrets.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: datahub
  app.kubernetes.io/component: data-catalog
  app.kubernetes.io/part-of: rpi-k8s-platform
