apiVersion: flink.apache.org/v1beta1
kind: FlinkSessionJob
metadata:
  name: indicators-math-operator
  namespace: flink
  labels:
    app: flink-trading-session
    job: indicators-math-operator
    pipeline-stage: compute
    category: math-operator
spec:
  deploymentName: flink-trading-session
  job:
    jarURI: s3://flink-jobs/java/indicators-math-operator.jar
    entryClass: io.rpi.flink.indicators.mathop.MathOperatorJob
    args:
      - "--kafka.bootstrap.servers"
      - "trading-kafka-kafka-bootstrap.data-services.svc.cluster.local:9092"
      - "--kafka.source.topic"
      - "market.bar.v1"
      - "--kafka.sink.topic"
      - "features.indicators.v1"
      - "--kafka.group.id"
      - "flink-java-mathop"
      - "--schema.registry.url"
      - "http://apicurio-registry.data-services.svc.cluster.local:8080/apis/registry/v2"
      - "--category.label"
      - "math_operator"
      - "--buffer.size"
      - "60"
    parallelism: 1
    upgradeMode: savepoint
    state: suspended
