apiVersion: flink.apache.org/v1beta1
kind: FlinkSessionJob
metadata:
  name: indicators-volume
  namespace: flink
  labels:
    app: flink-trading-session
    job: indicators-volume
    pipeline-stage: compute
    category: volume
spec:
  deploymentName: flink-trading-session
  job:
    jarURI: s3://flink-jobs/java/indicators-volume.jar
    entryClass: io.rpi.flink.indicators.volume.VolumeJob
    args:
      - "--kafka.bootstrap.servers"
      - "trading-kafka-kafka-bootstrap.data-services.svc.cluster.local:9092"
      - "--kafka.source.topic"
      - "market.bar.v1"
      - "--kafka.sink.topic"
      - "features.indicators.v1"
      - "--kafka.group.id"
      - "flink-java-volume"
      - "--schema.registry.url"
      - "http://apicurio-registry.data-services.svc.cluster.local:8080/apis/registry/v2"
      - "--category.label"
      - "volume"
    parallelism: 1
    upgradeMode: savepoint
    state: suspended
