apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secret.yaml
  - ingress.yaml

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/name: airbyte
      app.kubernetes.io/component: elt
      app.kubernetes.io/part-of: rpi-k8s-platform
